[package]
name = "vaultwarden_ldap"
version = "0.5.0"
authors = ["ViViDboarder <vividboarder@gmail.com>"]
edition = "2018"

[dependencies]
ldap3 = "0.6"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
reqwest = "0.9"
serde_json = "1.0"
thiserror = "1.0"
anyhow = "1.0"
